apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplicationVersion
metadata:
  name: mysql
  labels:
    application.kubesphere.io/operator-app: clickhouse
spec:
  name: "MySQL"
  screenshots: |
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
    - https://github.com/radondb/radondb-clickhouse-kubernetes/raw/main/document/_images/logo_radondb.svg
  changeLog:
    "Distributed引擎支持currentDatabase函数|增强备份恢复功能"
  operatorVersion: "1.0.1"
  appVersion: "20.1"
  icon: "/assets/click-house-green.svg"
  owner: "RadonDB"
status:
  state: active
