apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplication
metadata:
  name: postgresql
spec:
  # Add fields here
  name: "PostgreSQL"
  description: "PostgreSQL 是备受业界青睐的关系型数据库，尤其是在地理空间和移动领域，具有自动备份、在线扩容以及监控告警等各种管理功能。"
  description_en: "PostgreSQL is hot relational database for the industry,,,,"
  abstraction: |
    - 支持自动 Failover，提供HA功能；
    - 提供PostgreSQL大部分常用参数修改接口，方便调整参数；
    - 支持 PostGIS插件，为 PostgreSQL 提供了存储、查询和修改空间关系的能力；
    - 提供实时监控、健康检查、日志自动清理等功能；
  operator: "admin"
  icon: "https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/main/docs/images/logo_radondb-mysql.png"
  owner: "RadonDB"
status:
  state: active
